# Generated by Django 4.2.7 on 2024-01-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECB_APP', '0002_rbi_main2_economic_sector_of_borrower_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rbi_main2',
            old_name='S_No',
            new_name='SI_NO',
        ),
    ]
