# Generated by Django 4.2.7 on 2024-01-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECB_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbi_main2',
            name='Economic_sector_of_borrower',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='rbi_main2',
            name='Month',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='rbi_main2',
            name='S_No',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='rbi_main2',
            name='Year',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterModelTable(
            name='rbi_main2',
            table='rbi_ecb',
        ),
    ]
