# Generated by Django 4.2.7 on 2024-01-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECB_APP', '0003_rename_s_no_rbi_main2_si_no'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rbi_main2',
            table='new_2',
        ),
    ]
