# Generated by Django 5.0 on 2024-01-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rbi_odi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sr_No', models.CharField(blank=True, max_length=500, null=True)),
                ('Name_of_the_Indian_Party', models.CharField(blank=True, max_length=500, null=True)),
                ('Name_of_the_JV_or_WOS', models.CharField(blank=True, max_length=500, null=True)),
                ('Whether_JV_or_WOS', models.CharField(blank=True, max_length=500, null=True)),
                ('Overseas_Country', models.CharField(blank=True, max_length=500, null=True)),
                ('Major_Activity', models.CharField(blank=True, max_length=500, null=True)),
                ('FC_Equity', models.CharField(blank=True, max_length=5000, null=True)),
                ('FC_Loan', models.CharField(blank=True, max_length=500, null=True)),
                ('FC_Guarantee_Issued', models.CharField(blank=True, max_length=500, null=True)),
                ('FC_Total', models.CharField(blank=True, max_length=500, null=True)),
                ('Month', models.CharField(blank=True, max_length=500, null=True)),
                ('Year', models.CharField(blank=True, max_length=500, null=True)),
                ('date_scraped', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'rbi_odi',
            },
        ),
    ]
