# Generated by Django 5.0 on 2024-01-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ODI_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rbi_odi',
            name='FC_Equity',
        ),
        migrations.RemoveField(
            model_name='rbi_odi',
            name='FC_Guarantee_Issued',
        ),
        migrations.RemoveField(
            model_name='rbi_odi',
            name='FC_Loan',
        ),
        migrations.RemoveField(
            model_name='rbi_odi',
            name='FC_Total',
        ),
        migrations.RemoveField(
            model_name='rbi_odi',
            name='Name_of_the_JV_or_WOS',
        ),
        migrations.RemoveField(
            model_name='rbi_odi',
            name='Sr_No',
        ),
        migrations.RemoveField(
            model_name='rbi_odi',
            name='Whether_JV_or_WOS',
        ),
        migrations.RemoveField(
            model_name='rbi_odi',
            name='id',
        ),
        migrations.AddField(
            model_name='rbi_odi',
            name='Equity',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='rbi_odi',
            name='Guarantee_Issued',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='rbi_odi',
            name='Loan',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='rbi_odi',
            name='Name_of_the_JV_WOS',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rbi_odi',
            name='SI_NO',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rbi_odi',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='rbi_odi',
            name='Whether_JV_WOS',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rbi_odi',
            name='Major_Activity',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rbi_odi',
            name='Month',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rbi_odi',
            name='Name_of_the_Indian_Party',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rbi_odi',
            name='Overseas_Country',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rbi_odi',
            name='Year',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rbi_odi',
            name='date_scraped',
            field=models.DateTimeField(default=models.DateTimeField(auto_now_add=True)),
        ),
    ]
