# Generated by Django 4.2.7 on 2024-01-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ODI_APP', '0002_remove_rbi_odi_fc_equity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rbi_odi',
            name='Equity',
        ),
        migrations.RemoveField(
            model_name='rbi_odi',
            name='Guarantee_Issued',
        ),
        migrations.RemoveField(
            model_name='rbi_odi',
            name='Loan',
        ),
        migrations.RemoveField(
            model_name='rbi_odi',
            name='Total',
        ),
        migrations.AddField(
            model_name='rbi_odi',
            name='FC_Equity',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rbi_odi',
            name='FC_Guarantee_Issued',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rbi_odi',
            name='FC_Loan',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rbi_odi',
            name='FC_Total',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterModelTable(
            name='rbi_odi',
            table='odi',
        ),
    ]
