# Generated by Django 4.2.9 on 2024-02-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ODI_APP', '0003_remove_rbi_odi_equity_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rbi_odi',
            table='rbi_odi',
        ),
    ]
